# Generated by Django 3.0.3 on 2020-03-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200109_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='DEFAULT TITLE', max_length=50)),
                ('description', models.CharField(default='DEFAULT DESCRIPTION', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='exists',
            field=models.IntegerField(default=0),
        ),
    ]
